Newsweek home page
helciodev/newsweek-site-clone pull request #2
Opened 2020-10-28 21:19 UTC by helciodev

In this project,  I was tasked to recreate a clone from the newsweek.com site homepage using front-end technologies like HTML and  CSS but mainly the framework from Twitter, Bootstrap. 
The project has the following features:

- Navbar with nav list items as blocks.
- Main section 
- footer with footer nav list items and footer nav links and social links.

2020-10-28 22:45 UTC, Temmarie requested changes
## Changes Required! :recycle: 
### Hello @helciodev ! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png)

### You have done an astounding work in this project so far. However, there are some necessary changes to be made before it can be approved.

 
### Recommended




**Navigation Bar**
- [x] The info bar which holds the logo needs more padding and the logo itself should have a larger width.

- [x] The font-size of the "Search" placeholder in the nav-bar should be reduced.

- [x] The debate column in your project has a smaller width than the original.

**My Turn**
- [x] The images in the "My Turn" section are of different sizes, please make them uniform.

**More Stories**
- [x] The "More stories" section has a glitch, it's not gliding as smoothly as that of the actual page.

**Free Sign Up Form**
- [ ] You have re-arranged the  position of the page content. The "Free Sign Up" Form should come after the "Opinions".

**The Magazine**

- [ ] The images in this section should be larger. Refer to the [Newsweek site](https://www.newsweek.com/) to see the comparison.

**Newsletter**
- [ ] This section needs more work as well. The image and form does not fit the proportions of the Newsweek site.

**Footer**

- [ ] The footer also needs to be fixed. The font-size is larger than that of the actual site.

- [ ] The logo has a different color from the actual site's.

**Screen Sizing**
- [ ] The Debate section and the Opinions section in the medium screen size(768px ) should take the whole space.

- [ ] You have extra features in your project that is not reflected in the Newsweek site, please remove those.

- [ ] The Subscribe and Newsletter sections should fill the entire row. 

- [ ] The footer is not displaying as it should.

 

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review @tamara._ :wink: 
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2020-10-30 11:05 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @helciodev 

Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [x] Update the `href` attribute as mentioned in inline comment.


### MAGAZINE Section
- [x] Add margin-top on other cards as highlighted in the screenshot

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://helciodev.github.io/newsweek-site-clone/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97697339-afca8a80-1ac8-11eb-8fd4-80092f846320.png)|![clone](https://user-images.githubusercontent.com/29689273/97697344-b1944e00-1ac8-11eb-97dd-d23e0a06d0af.png)|


### EDITOR'S PICK Section
- [x] Please add 4 cards in large screen as original page

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://helciodev.github.io/newsweek-site-clone/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97697595-059f3280-1ac9-11eb-84c2-acb6b1ecdf0d.png)|![clone](https://user-images.githubusercontent.com/29689273/97697602-08018c80-1ac9-11eb-84d0-96573f189848.png)|



##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-30 11:05 UTC, umairarshadbutt commented on assets/sass/style.css
> +  background: #f72210 !important;
Remove `!important`

2020-10-30 11:05 UTC, umairarshadbutt commented on assets/sass/style.css
> +  color: #3b5998 !important;
Remove `!important`

2020-10-30 11:05 UTC, umairarshadbutt commented on assets/sass/style.css
> +  color: #1da1f2 !important;
Remove `!important`

2020-10-30 11:05 UTC, umairarshadbutt commented on assets/sass/style.css
> +  color: #405de6 !important;
Remove `!important`

2020-10-30 11:05 UTC, umairarshadbutt commented on assets/sass/style.css
> +  color: #3592d5 !important;
Remove `!important`

2020-10-30 11:05 UTC, umairarshadbutt commented on assets/sass/style.css
> +  color: #0077b5 !important;
Remove `!important`

2020-10-30 11:05 UTC, umairarshadbutt commented on assets/sass/style.css
> +    color: #f72210 !important;
Remove `!important`

2020-10-30 11:05 UTC, umairarshadbutt commented on assets/sass/style.css
> +    margin-top: -4rem !important;
Remove `!important`

2020-10-30 11:05 UTC, umairarshadbutt commented on assets/sass/style.css
> +    width: 50% !important;
Remove `!important`

2020-10-30 11:05 UTC, umairarshadbutt commented on index.html
> +          <li class="mr-3"><a class="text-secondary text-decoration-none" href="">
Add `#` or `URL` in `href` attribute

2020-10-30 14:06 UTC, ioilmio approved these changes
## Congrats @helciodev you fix all the issues pointed out from the previous reviewers, your project is approved 👍🏼  🎉

2020-10-30 14:15 UTC, merged